/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import DAO.LichLamViecDAO;
import Models.LichLamViec;
import Services.AuthNhanVien;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class LichLamViecFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public LichLamViecFrame() {
        initComponents();
        initTable();
        fillTable();
    }

    public void phanQuyen() {
        btnSua.setEnabled(false);
        if (AuthNhanVien.isManager() != 1) {
            btnSua.setEnabled(true);
        }
    }

    DefaultTableModel tableModel_lich_lam_viec = new DefaultTableModel();
    List<LichLamViec> listLLV = new ArrayList<>();

    public void initTable() {
        String[] cols = new String[]{"Mã Lịch", "Mã Nhân Viên", "Tên Nhân Viên", "Vai Trò", "Ngày Làm Việc", "Ca Làm Việc"};
        tableModel_lich_lam_viec.setColumnIdentifiers(cols);
        tbl_lich_lam_viec.setModel(tableModel_lich_lam_viec);
    }

    public void fillTable() {
        tableModel_lich_lam_viec.setRowCount(0);
        LichLamViecDAO llvDAO = new LichLamViecDAO();
        List<LichLamViec> list = llvDAO.getData();

        for (LichLamViec lichLamViec : list) {
            tableModel_lich_lam_viec.addRow(new Object[]{
                lichLamViec.getMaLich(),
                lichLamViec.getMaNhanVien(),
                lichLamViec.getTenNhanVien(),
                lichLamViec.getVaiTro(),
                lichLamViec.getNgayLamViec(),
                lichLamViec.getCaLamViec()
            });
        }
    }

    public void update() {
        String MalichLamViec = txt_ma_lich_lam_viec.getText().trim();
        String MaNhanVien = txt_ma_nhan_vien.getText().trim();
        String NgayLamViec = txt_ngay_lam_viec.getText().trim();
        String CaLamViec = (String) cbo_ca_lam_viec.getSelectedItem();

        if (MalichLamViec.isEmpty() || MaNhanVien.isEmpty() || NgayLamViec.isEmpty() || CaLamViec.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin.");
            return;
        }

        try {
            LichLamViec llv = new LichLamViec();
            LichLamViecDAO llvDAO = new LichLamViecDAO();

            llv.setMaLich(Integer.parseInt(MalichLamViec));
            llv.setMaNhanVien(MaNhanVien);
            llv.setNgayLamViec(NgayLamViec);
            llv.setCaLamViec(CaLamViec);

            int choice = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn cập nhật lịch làm việc không?");
            if (choice == JOptionPane.YES_OPTION) {
                if (llvDAO.update(llv)) {
                    JOptionPane.showMessageDialog(this, "Cập nhật lịch làm việc thành công.");
                    fillTable();
                } else {
                    JOptionPane.showMessageDialog(this, "Cập nhật lịch làm việc thất bại.");
                }
            } else {
                JOptionPane.showMessageDialog(this, "Yêu cầu đã bị hủy.");
            }

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        txt_ma_lich_lam_viec = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_ma_nhan_vien = new javax.swing.JTextField();
        txt_ngay_lam_viec = new javax.swing.JTextField();
        btnSua = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_lich_lam_viec = new javax.swing.JTable();
        cbo_ca_lam_viec = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Mã lịch làm việc");

        txt_ma_lich_lam_viec.setPreferredSize(new java.awt.Dimension(64, 30));
        txt_ma_lich_lam_viec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ma_lich_lam_viecActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Mã nhân viên");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Ngày làm việc");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Ca làm việc");

        txt_ma_nhan_vien.setPreferredSize(new java.awt.Dimension(64, 30));
        txt_ma_nhan_vien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ma_nhan_vienActionPerformed(evt);
            }
        });

        txt_ngay_lam_viec.setPreferredSize(new java.awt.Dimension(64, 30));
        txt_ngay_lam_viec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_ngay_lam_viecActionPerformed(evt);
            }
        });

        btnSua.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSua.setText("Cập nhật");
        btnSua.setPreferredSize(new java.awt.Dimension(72, 30));
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btn4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn4.setText("Làm mới");
        btn4.setPreferredSize(new java.awt.Dimension(72, 30));
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        tbl_lich_lam_viec.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbl_lich_lam_viec.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_lich_lam_viecMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_lich_lam_viec);

        cbo_ca_lam_viec.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ca 1: 06h00 - 14h00", "Ca 2: 14h00 - 22h00", "Ca 3: 22h00 - 06h00" }));
        cbo_ca_lam_viec.setPreferredSize(new java.awt.Dimension(136, 30));

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Lịch làm việc");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quay_lai.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(128, 75));
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel9MouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_ma_lich_lam_viec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ma_nhan_vien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txt_ngay_lam_viec, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbo_ca_lam_viec, 0, 470, Short.MAX_VALUE))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txt_ma_lich_lam_viec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnSua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txt_ma_nhan_vien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txt_ngay_lam_viec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(cbo_ca_lam_viec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_ma_lich_lam_viecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ma_lich_lam_viecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ma_lich_lam_viecActionPerformed

    private void txt_ma_nhan_vienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ma_nhan_vienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ma_nhan_vienActionPerformed

    private void txt_ngay_lam_viecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_ngay_lam_viecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_ngay_lam_viecActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        update();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
        txt_ma_lich_lam_viec.setText("");
        txt_ma_nhan_vien.setText("");
        txt_ngay_lam_viec.setText("");
        cbo_ca_lam_viec.setSelectedIndex(0);
        fillTable();
    }//GEN-LAST:event_btn4ActionPerformed

    private void tbl_lich_lam_viecMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_lich_lam_viecMouseClicked
        // TODO add your handling code here:
        int row = tbl_lich_lam_viec.getSelectedRow();
        if (row >= 0) {
            String maLich = tbl_lich_lam_viec.getValueAt(row, 0).toString();
            String maNhanVien = tbl_lich_lam_viec.getValueAt(row, 1).toString();
            String ngayLamViec = tbl_lich_lam_viec.getValueAt(row, 2).toString();
            String caLamViec = tbl_lich_lam_viec.getValueAt(row, 3).toString();

            txt_ma_lich_lam_viec.setText(maLich);
            txt_ma_nhan_vien.setText(maNhanVien);
            txt_ngay_lam_viec.setText(ngayLamViec);
            cbo_ca_lam_viec.setSelectedItem(caLamViec);
        }
    }//GEN-LAST:event_tbl_lich_lam_viecMouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        this.dispose();
        SystemFrame sFrame = new SystemFrame();
        sFrame.setLocationRelativeTo(null);
        sFrame.setVisible(true);
        return;
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel9MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LichLamViecFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LichLamViecFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LichLamViecFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LichLamViecFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LichLamViecFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn4;
    private javax.swing.JButton btnSua;
    private javax.swing.JComboBox<String> cbo_ca_lam_viec;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_lich_lam_viec;
    private javax.swing.JTextField txt_ma_lich_lam_viec;
    private javax.swing.JTextField txt_ma_nhan_vien;
    private javax.swing.JTextField txt_ngay_lam_viec;
    // End of variables declaration//GEN-END:variables
}
